string=input("Enter a string: ")
a=string.replace("a","")
e=a.replace('e',"")
i=e.replace('i', "")
o=i.replace('o',"")
u=o.replace('u',"")
A=u.replace('A',"")
E=A.replace('E',"")
I=E.replace('I',"")
O=I.replace('O',"")
U=O.replace("U","")
print("Without any vowel:",U)